# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{tagomatic}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Daniel Lukic"]
  s.date = %q{2009-11-02}
  s.default_executable = %q{tagomatic}
  s.description = %q{= tagomatic

Simple command-line mp3 tagger based on mp3info gem. Supports folder-specific configuration files.

Another mp3 tagger the world does not need.

But I needed it. I have a large collection of old mp3 files. From times when tagging was mostly
based on the file and folder names. When v2 tags where nowhere close..

Modes of operation:

* The tagger will try to guess the tags from the full file path by applying a set of known formats.
* The tagger will apply specific tags given on the command-line.
* The tagger will match specific formats given on the command-line.
* Arbitraty combination of the before-mentioned modes.

The scanner supports recursive folder handling. Of course.

Right now v2 tags are the focus.

It is probably best to call this alpha ware.

== Copyright

Copyright (c) 2009 Daniel Lukic. See LICENSE for details.
}
  s.email = %q{daniel.lukic@berlinfactor.com}
  s.executables = ["tagomatic"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     ".idea/ant.xml",
     ".idea/compiler.xml",
     ".idea/dictionaries/dl.xml",
     ".idea/dynamic.xml",
     ".idea/encodings.xml",
     ".idea/inspectionProfiles/Project_Default.xml",
     ".idea/inspectionProfiles/profiles_settings.xml",
     ".idea/misc.xml",
     ".idea/modules.xml",
     ".idea/projectCodeStyle.xml",
     ".idea/tagomatic.iml",
     ".idea/templateLanguages.xml",
     ".idea/uiDesigner.xml",
     ".idea/vcs.xml",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/tagomatic",
     "lib/monkey/string.rb",
     "lib/tagomatic/format_compiler.rb",
     "lib/tagomatic/format_matcher.rb",
     "lib/tagomatic/info_updater.rb",
     "lib/tagomatic/local_options_matcher.rb",
     "lib/tagomatic/logger.rb",
     "lib/tagomatic/main.rb",
     "lib/tagomatic/mp3info_wrapper.rb",
     "lib/tagomatic/object_factory.rb",
     "lib/tagomatic/options.rb",
     "lib/tagomatic/options_parser.rb",
     "lib/tagomatic/scanner.rb",
     "lib/tagomatic/system_configuration.rb",
     "lib/tagomatic/tagger.rb",
     "tagomatic.gemspec",
     "test/data/sorted/80s/Peter_Schilling/Fast_alles_konstruiert/01-Fast_alles_konstruiert.mp3",
     "test/data/sorted/80s/Peter_Schilling/Fast_alles_konstruiert/02-Dann_truegt_der_schein.mp3",
     "test/helper.rb",
     "test/test_tagomatic.rb"
  ]
  s.homepage = %q{http://github.com/DanielLukic/tagomatic}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Simple command-line mp3 tagger based on mp3info gem. Supports folder-specific configuration files.}
  s.test_files = [
    "test/helper.rb",
     "test/test_tagomatic.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<ruby-mp3info>, [">= 0"])
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<ruby-mp3info>, [">= 0"])
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<ruby-mp3info>, [">= 0"])
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

